name: Update README

on:
  workflow_run:
    workflows: ["Deploy to OSS"]      # 修改为你的站点发布工作流 name
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BLOG_TOKEN }}
          repository: Enigmatisms/Enigmatisms

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install
        run: pip install feedparser

      - name: Update
        run: python update_blog.py

      - name: Commit
        env:
          TZ: Asia/Shanghai
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m \
          ":beers: Update from BlogRepo at \
          $(date +"%Y-%m-%d %H:%M") \
          " --allow-empty
          git push